### PR TITLE
added switch between warnings and errors output type

### PR DESCRIPTION
**Pull request by lsvhome**
switching between warnings and errors with TreatWarningsAsErrors property variable of *.csproj

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
@Isvhome I don't follow why you're proposing this change. Could you please explain the reason?

**Comment by lsvhome** [comment]
When I use tslint for specific configurations I want to separate two workflows: 
1) Debug mode when tslint warnings allowed
2) Release mode when tslint warnings should be fixed

In my case csproj contains standatd property TreatWarningsAsErrors

`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">`
`    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>`
`  </PropertyGroup>`
`  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">`
`    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>`
`  </PropertyGroup>`

And I use TreatWarningsAsErrors to switch between TSLint warnings modes.
Patch don't break base functionality but allows some customization.
I mean that way is usefiul for people who use package.

best regards and thank you for your work

**Comment by JoshuaKGoldberg** [comment]
How do you see this interacting with https://github.com/palantir/tslint/pull/1738?

**Comment by JoshuaKGoldberg** [comment]
@Isvhome I actually really like your change! But, it needs a few things before merge:
* It should be documented in README.md
* It should have a couple tests to verify the cases
* I'll need to play around with it

If you can do the first two, I'll do the third. Otherwise I can try to get to all three.

**Pull request closed without merging**
