### PR TITLE
Changed exit code check to be != 0

### PR DESCRIPTION
**Pull request by rylek90**
I've wanted to do it by myself but found this branch already. I really need to have this feature as soon as possible. 

Thanks ;)

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Haha sure.

**Comment by rylek90** [comment]
Thanks, is it possible to push it to nuget?

**Comment by JoshuaKGoldberg** [comment]
I'd still like to test it a bit. Will do & get back to you today.

**Comment by JoshuaKGoldberg** [comment]
Seems to work well. Published as https://www.nuget.org/packages/TSLint.MSBuild/1.1.1!

**Comment by rylek90** [comment]
Thank you!

**Pull request merged**
