### PR TITLE
Add TSLintFileListDisabled property

### PR DESCRIPTION
**Pull request by brettjacobson**
https://github.com/JoshuaKGoldberg/TSLint.MSBuild/issues/71

Added property TSLintFileListDisabled, to prevent passing the files list on the command line, but instead expect to pull them from the Project setting file (tsconfig.json type file).
Fixed old TSLintCliLocalTSLint test that was failing.
Updated to v1.1.0

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Other than merge conflicts (you'll need to rebase) LGTM!

**Comment by brettjacobson** [comment]
Okay I think I got things resolved!

**Comment by JoshuaKGoldberg** [comment]
:+1: LGTM. Thanks!

**Comment by JoshuaKGoldberg** [comment]
https://www.nuget.org/packages/TSLint.MSBuild/1.1.0

**Pull request merged**
