### PR TITLE
Fix false error when TSLintDisabled is true

### PR DESCRIPTION
**Pull request by grantborthwick**
When TSLintDisabled is true, TSLintErrorCode never gets set to 0, so this error task always emits an error.

Other possible solutions - I'm open to suggestions:
* Check TSLintDisabled from the target conditions
* Set TSLintErrorCode to 0 if TSLintDisabled is true

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Hi sorry, this must have dropped off my radar! Will review today.

**Comment by JoshuaKGoldberg** [comment]
Actually, @grantborthwick, what is the use case for both `TSLintDisabled` and `TSLintBreakBuildOnError` being true?

**Comment by grantborthwick** [comment]
@JoshuaKGoldberg - one of our projects has TSLintBreakBuildOnError set to true and usually runs TSLint. I'm invoking msbuild from a local script and want to allow the process to keep going despite TSLint errors. If there are errors, we'll catch them when building from Visual Studio or from a PR build.

Right now I'm setting both TSLintDisabled and TSLintBreakBuidOnError globally to false from my script as a workaround.

**Review by JoshuaKGoldberg — APPROVED** [review]
SGTM. Thanks!

**Comment by JoshuaKGoldberg** [comment]
This should be published as https://www.nuget.org/packages/TSLint.MSBuild/2.0.2. Enjoy!

**Pull request merged**
