### PR TITLE
Add timestamp file flag

### PR DESCRIPTION
**Pull request by PaytonQuinn**

### CODE REVIEW

**Comment by PaytonQuinn** [comment]
Hi Josh,

Thanks!  I think there’s actually a small issue with this change which I’m still investigating.  Please hold off on merging for the time being.

Thanks,

Payton

On Nov 14, 2018, at 8:40 AM, Josh Goldberg <notifications@github.com<mailto:notifications@github.com>> wrote:


@JoshuaKGoldberg approved this pull request.

Awesome, thanks for this @PaytonQuinn<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPaytonQuinn&data=02%7C01%7Cpaquinn%40microsoft.com%7C334a5b51571b4a6a540408d64a4fd669%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636778104097249460&sdata=iFjbb3Rf1k6VdT0gXvonCy0WfIyS9o5%2Fk67b5VTfvzo%3D&reserved=0>! Looks like this should work perfectly. I'll play with it a bit locally just to be sure, then play with your formatting a bit and merge it in soon. 👍

**Comment by JoshuaKGoldberg** [comment]
Ok, good luck!

**Comment by PaytonQuinn** [comment]
Fixed.  This is ready for merge now.

**Comment by PaytonQuinn** [comment]
Thanks! Will you be handling generating a new release to nuget.org?

**Comment by JoshuaKGoldberg** [comment]
Just published as 1.4.0: https://www.nuget.org/packages/TSLint.MSBuild/1.4.0

**Pull request merged**
